# Generated by Django 5.2.5 on 2025-11-06 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('startDate', models.CharField(max_length=200)),
                ('endDate', models.CharField(blank=True, max_length=200)),
                ('isCurrentRole', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
