# Generated by Django 5.2.5 on 2025-11-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='prof_description',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='prof_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
