# Generated by Django 5.2.5 on 2025-11-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_appuser_prof_description_appuser_prof_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='prof_description',
            new_name='prof_summary',
        ),
    ]
