# Generated by Django 5.2.5 on 2025-11-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_prof_description_appuser_prof_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='prof_summary',
            field=models.TextField(blank=True),
        ),
    ]
