# Generated by Django 5.2.5 on 2025-11-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_education_user_alter_experience_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.TextField(max_length=500),
        ),
    ]
