# Generated by Django 5.2.5 on 2025-11-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
